### ISSUE TITLE
 rss spec: pubDate 

### ISSUE THREAD

**Issue by igormartynov** [JohnnyTheTank/apiNG-plugin-rss#12]
rss spec declares: pubDate not publishedDate

l.83 https://github.com/JohnnyTheTank/apiNG-plugin-rss/blob/master/src/aping-rss-helper.js

https://validator.w3.org/feed/docs/rss2.html

**Comment by JohnnyTheTank** [comment]
fixed. thank you @igormartynov

**Comment by JohnnyTheTank** [comment]
@igormartynov do you use aping?
