### ISSUE TITLE
Change RSS->JSON parser

### ISSUE THREAD

**Issue by JohnnyTheTank** [JohnnyTheTank/apiNG-plugin-rss#5]
- https://gist.github.com/cmbaughman/9370106
- http://jsfiddle.net/BkXyQ/6/
- https://davidwalsh.name/convert-xml-json
- (YQL) http://tutorialzine.com/2010/02/feed-widget-jquery-css-yql/
- (YQL) http://www.javascriptkit.com/dhtmltutors/yqlfeeds.shtml
- (YQL) http://james.padolsey.com/snippets/using-yql-with-jsonp/

**Comment by sorinsfirlogea** [comment]
Or https://rss2json.com

**Comment by JohnnyTheTank** [comment]
done, ty @sorinsfirlogea

**Comment by sorinsfirlogea** [comment]
thank you too, would be cool to upload it on http://cdn.jsdelivr.net/aping.plugin-rss/latest/aping-plugin-rss.min.js

**Comment by JohnnyTheTank** [comment]
already done. it's maybe cache

**Comment by JohnnyTheTank** [comment]
will be automaticly updated in the next days
